name: Build

on:
  push:
    branches:
      - master

jobs:

  buildTestRelease:

    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        include:
          - os: windows-latest
            extension: ".zip"
            runtime: "win-x64"
            platform: "win"
          - os: ubuntu-latest
            extension: ".tar.gz"
            runtime: "linux-x64"
            platform: "linux"
          - os: macos-latest
            runtime: "osx-x64"
            extension: ".zip"
            platform: "osx"
        node_version: [14.x]
        dotnet_version: ['2.1.807']
      fail-fast: false

    runs-on: ${{ matrix.os }}

    env:
      PROJECT_NAME: 'OpenExo.Node'
      DAEMON: '1.0.15'
      ARCH: 'x64'
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    steps:

    - uses: actions/checkout@v1
      name: Checkout

    - name: Setup Node.js (${{ matrix.node_version }})
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: Variables
      run: |
        echo "::set-env name=VERSION::$(npm run version --silent)"
        echo "::set-env name=RELEASE_CONFIGURATION::${{ matrix.runtime }}"

    - name: Tooling
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install snapd
        sudo snap install --classic snapcraft

    - name: Download OpenExo Chain
      shell: pwsh
      run: |
        echo ${env:PATH}
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        $url = "https://github.com/Fluidchains/Divergenti/releases/download/${{ env.DAEMON }}/OpenExo.Node-${{ env.DAEMON }}-${{ matrix.platform }}-${{ env.ARCH }}${{ matrix.extension }}"
        $output = Join-Path -Path "./" -ChildPath "daemon${{ matrix.extension }}"
        Write-Output "Url: $url"
        Write-Output "Path: $output"
        $start_time = Get-Date
        (New-Object System.Net.WebClient).DownloadFile($url, $output)
        Write-Output "Time taken: $((Get-Date).Subtract($start_time).Seconds) second(s)"

    - name: Unpack (Windows)
      if: matrix.os == 'windows-latest'
      run: 7z x daemon${{ matrix.extension }} -odaemon

    - name: Unpack (Mac)
      if: matrix.os == 'macos-latest'
      run: unzip -a daemon${{ matrix.extension }} -d daemon

    - name: Unpack (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        mkdir daemon
        tar -xvzf daemon${{ matrix.extension }} -C daemon

    - name: Prepare for app notarization
      if: startsWith(matrix.os, 'macos')
      run: |
        mkdir -p ~/private_keys/
        echo '${{ secrets.api_key }}' > ~/private_keys/AuthKey_${{ secrets.api_key_id }}.p8

    - name: Install (npm)
      run: npm install

    - name: Build and Publish
      run: npm run publish:${{ matrix.platform }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CSC_LINK: ${{ secrets.CSC_LINK }}
        CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
        appleId: ${{ secrets.appleId }}
        appleIdPassword: ${{ secrets.appleIdPassword }}
